### ISSUE TITLE
Are the multiple drugs in the column `drug` in data files the group of drugs being compared in the trial at the same time?

### ISSUE THREAD

**Issue by jasperhyp** [futianfan/clinical-trial-outcome-prediction#4]
Thanks in advance!

**Comment by futianfan** [comment]
yes, each line represents a trial, which may contain multiple drugs in the trial.

**Comment by jasperhyp** [comment]
Thanks!  But how do I know which drug in a list is the drug that the label of success/fail is assigned to?

**Comment by futianfan** [comment]
good question, trials may test one drug or drug combination, so we do not need to discriminate which one is the tested drug.

**Comment by jasperhyp** [comment]
Hmmm interesting.  I am thinking about two scenarios.  First, in some cases a certain drug that does not work (usually placebos, sometimes vitamins perhaps, lists of drugs that contain them are present in the dataset) is used for the control group, and I guess they should be tested.  Second, in some cases a known effective drug might be the control group (aka **Active Comparator**), especially in some cancer treatment studies.  This might not lead to information leakage if we assume the choice of experiment for a certain drug to be unbiased, but probably would make it ambiguous as to which drug/drug combinations are being tested.  Anyways, thanks for collecting this nice dataset!

**Comment by futianfan** [comment]
thanks for pointing out it. That is really a problem. But for the first scenario, we did remove the placebo. For second scenario, we have not found good solution to do it. manually labelling it is too costly. Thanks a lot again!

**Comment by futianfan** [comment]
https://github.com/futianfan/clinical-trial-outcome-prediction/blob/f8f31599fa7d83cc4967acbf43b86352d702c32f/benchmark/data_split.py#L398 
this is the code we remove placebo, it did promote the accuracy.

**Comment by jasperhyp** [comment]
> https://github.com/futianfan/clinical-trial-outcome-prediction/blob/f8f31599fa7d83cc4967acbf43b86352d702c32f/benchmark/data_split.py#L398
> 
> 
> this is the code we remove placebo, it did promote the accuracy.

Wonderful!  Thanks for referring me to this.  I assume the second issue might be ameliorated if the notes on clinicaltrials.gov for the specific trial can be analyzed, maybe through some NLP information extraction methods.  It might contain a general description of which drug/drug combination is being tested.  But your paper is already wonderful!  Thanks again for sharing the dataset.

**Comment by futianfan** [comment]
thanks for your attention and suggestions! we will consider your suggestions!
