### ISSUE TITLE
Where can I possibly find the complete version of `drugbank_mini.csv`?

### ISSUE THREAD

**Issue by jasperhyp** [futianfan/clinical-trial-outcome-prediction#5]
Hi,  Thanks again for curating this dataset!  I was just wondering where I can find the complete version of `drugbank_mini.csv`, since using drug names as query through drugbank's vocabulary file does not always output a valid drugbank id.  `drugbank_mini.csv` contains more information and might be useful to map those ambiguous ones to correct ids.

**Comment by futianfan** [comment]
it is downloaded from drugbank website, https://go.drugbank.com/releases/latest
