### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by Federico-Agostinis** [futianfan/clinical-trial-outcome-prediction#6]
Hi,

thank you for your precious work.

I am trying to reproduce tutorial_HINT.ipynb but I found the following error

`---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-9-a99e1812caae> in <module>
----> 1 train_loader = csv_three_feature_2_dataloader(train_file, shuffle=True, batch_size=32)
      2 valid_loader = csv_three_feature_2_dataloader(valid_file, shuffle=False, batch_size=32)
      3 test_loader = csv_three_feature_2_dataloader(test_file, shuffle=False, batch_size=32)

~\Desktop\CLINICALTRIAL\HINT\dataloader.py in csv_three_feature_2_dataloader(csvfile, shuffle, batch_size)
    103 def csv_three_feature_2_dataloader(csvfile, shuffle, batch_size):
    104         with open(csvfile, 'r') as csvfile:
--> 105                 rows = list(csv.reader(csvfile, delimiter=','))[1:]
    106         ## nctid,status,why_stop,label,phase,diseases,icdcodes,drugs,smiless,criteria
    107         nctid_lst = [row[0] for row in rows]

~\Miniconda3\envs\predict_drug_clinical_trial\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1027: character maps to <undefined>`

Do you know how could I solve it?

Regards,
Federico

**Comment by futianfan** [comment]
hi Federico, the tutorial is out of date. can you follow the readme.md to run the script? thanks
