### ISSUE TITLE
Obtain the Full drugbank data

### ISSUE THREAD

**Issue by lck042** [futianfan/clinical-trial-outcome-prediction#7]
Great Work! Just one question: how can we get the full information for the drugbank data?  
I noticed that it can be downloaded from drugbank website, https://go.drugbank.com/releases/latest, but I am not sure how to pre-process it after we obtain the *full database.xml* file. Thanks!

**Comment by futianfan** [comment]
thanks for your interest. i uploaded the processed drugbank data in https://www.dropbox.com/s/angoirabxurjljh/drugbank_drugs_info.csv?dl=0 
let me know when you have other questions. thanks

**Comment by knightsay** [comment]
Hi thanks for the great work! Unfortunately the above Dropbox link seems no longer valid? If so, would you mind re-uploading it? Many thx!

**Comment by Puddin1066** [comment]
Yes, I agree, great work.  Did this link get fixed?
